import type { Metadata } from "next";
import Link from "next/link";
import { Logo } from "@/components/ui";

export const metadata: Metadata = { title: "Privacy & governance" };

const rows: [string, string][] = [
  ["Account", "Email, display name, and a scrypt-hashed password (or a GitHub identity if you sign in with GitHub). Sessions are HTTP-only, SameSite=Lax cookies."],
  ["Skills profile", "What you enter: skills, niches, rate floor, bio, portfolio links, excluded keywords. Used to score listings and write drafts. Nothing else is inferred about you."],
  ["Listings", "Only the listings you open or send from the extension (title, budget, description text, public client signals, URL). Never marketplace passwords, cookies, messages, or anything behind a login you didn't open."],
  ["Drafts & digests", "Proposal drafts, work-bench documents and the digest emails we composed for you."],
  ["Billing", "Stripe holds your card data; we store only the Stripe customer/subscription ids and plan status."],
  ["Usage & audit trail", "Counts of scored matches/drafts (for plan limits) and security events such as license rotation, with no listing content."],
];

export default function Privacy() {
  return (
    <div className="mx-auto max-w-3xl px-5 py-10">
      <Link href="/" aria-label="Home"><Logo /></Link>
      <h1 className="mt-10 text-4xl font-semibold tracking-tight">Privacy &amp; governance</h1>
      <p className="mt-3 text-[15px] leading-relaxed text-muted">
        GigRadar is a co-pilot: it finds gigs and drafts the pitch; you close the deal. This page says plainly what it does and doesn&apos;t do. This is a hackathon build — see the repository&apos;s <code className="font-mono text-ink">docs/COMPLIANCE.md</code> for the engineering detail and known gaps.
      </p>

      <h2 className="mt-10 text-xl font-semibold">What we store</h2>
      <dl className="mt-4 divide-y divide-line rounded-xl border border-line bg-surface/60">
        {rows.map(([k, v]) => (
          <div key={k} className="grid gap-1 px-5 py-4 sm:grid-cols-[170px_1fr]">
            <dt className="text-[13.5px] font-medium text-ink">{k}</dt>
            <dd className="text-[13.5px] leading-relaxed text-muted">{v}</dd>
          </div>
        ))}
      </dl>

      <h2 className="mt-10 text-xl font-semibold">What we never do</h2>
      <ul className="mt-3 list-disc space-y-2 pl-5 text-[14.5px] leading-relaxed text-muted">
        <li>Submit a proposal, message a client, or take any action on a marketplace on your behalf.</li>
        <li>Ask for or store your marketplace credentials, or act as you while logged in.</li>
        <li>Crawl marketplaces in the background or work around bot detection. The extension reads the page you have open, when you ask it to.</li>
        <li>Sell your data or use your profile or listings to train models.</li>
      </ul>

      <h2 className="mt-10 text-xl font-semibold">AI use</h2>
      <p className="mt-3 text-[14.5px] leading-relaxed text-muted">
        Draft text is generated by a third-party language model (configured by the operator) from your profile and the listing. Listing text is treated as untrusted data, never as instructions; links in drafts are limited to your own portfolio links; and every draft ships with a checklist telling you to verify it before sending. When no model is available a labelled, deterministic template is used.
      </p>

      <h2 className="mt-10 text-xl font-semibold">Your controls</h2>
      <ul className="mt-3 list-disc space-y-2 pl-5 text-[14.5px] leading-relaxed text-muted">
        <li><b className="text-ink">Export</b> everything we hold as JSON, and <b className="text-ink">delete</b> your account (and all linked data, plus your Stripe subscription) from <Link href="/dashboard/settings" className="text-accent underline-offset-2 hover:underline">Settings</Link>.</li>
        <li><b className="text-ink">License keys</b> are signed, never stored in plain form, and can be rotated or revoked instantly.</li>
        <li>Disable the email digest in your profile at any time.</li>
      </ul>

      <h2 className="mt-10 text-xl font-semibold">Marketplace terms</h2>
      <p className="mt-3 text-[14.5px] leading-relaxed text-muted">
        Upwork, Fiverr and Freelancer set their own rules about automation and data use. You are responsible for following them. GigRadar is not affiliated with or endorsed by any marketplace; fixture mode exists so the full loop can be evaluated without touching one.
      </p>
      <p className="mt-10 text-[13px] text-faint">Demo deployment: Stripe runs in test mode. No real charges are made.</p>
    </div>
  );
}
