/**
 * Embeds drizzle-kit's generated SQL migrations into a TS module so they travel with any bundler
 * (Next.js / Vercel serverless can't rely on reading ./drizzle at runtime).
 * Run via `npm run db:generate` (which calls drizzle-kit generate first).
 */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const dir = join(root, "drizzle");
const journal = JSON.parse(readFileSync(join(dir, "meta", "_journal.json"), "utf8")) as {
  entries: { idx: number; tag: string }[];
};

const known = new Set(readdirSync(dir).filter((f) => f.endsWith(".sql")));
const migrations = journal.entries
  .sort((a, b) => a.idx - b.idx)
  .map((e) => {
    const file = `${e.tag}.sql`;
    if (!known.has(file)) throw new Error(`Missing migration file ${file}`);
    const statements = readFileSync(join(dir, file), "utf8")
      .split("--> statement-breakpoint")
      .map((s) => s.trim())
      .filter(Boolean);
    return { id: e.tag, statements };
  });

const out = `// AUTO-GENERATED by scripts/embed-migrations.ts — do not edit.
export const MIGRATIONS: { id: string; statements: string[] }[] = ${JSON.stringify(migrations, null, 2)};
`;
writeFileSync(join(root, "src", "db", "migrations.generated.ts"), out);
console.log(`Embedded ${migrations.length} migration(s): ${migrations.map((m) => m.id).join(", ")}`);
